version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=transactions
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - db:/home/joe/github.com/Gophberg/TransactionAPI/pgdata:/var/lib/postgresql/data
volumes:
  db:
    driver: local
